CREATE DATABASE OutOfOfficeDb;
GO

USE OutOfOfficeDb;
GO


CREATE TABLE Employees(
	  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	  PasswordHash VARCHAR(MAX) NOT NULL,
	  Salt UNIQUEIDENTIFIER NOT NULL,
	  FullName VARCHAR(100) NOT NULL UNIQUE,
	  Subdivision INT NOT NULL,
	  Position INT NOT NULL,
	  IsActive BIT NOT NULL,
	  PeoplePartnerId INT NULL FOREIGN KEY REFERENCES Employees(ID),
	  OutOfOfficeBalance INT NOT NULL,
	  Photo VARBINARY(MAX) NULL
);
GO

CREATE TABLE LeaveRequests(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EmployeeId INT NOT NULL UNIQUE FOREIGN KEY REFERENCES Employees(ID),
	AbsenceReason INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	Comment VARCHAR(MAX) NULL,
	[Status] INT NOT NULL
);
GO

CREATE TABLE ApprovalRequests(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ApproverId INT NOT NULL FOREIGN KEY REFERENCES Employees(ID),
	LeaveRequestId INT NOT NULL UNIQUE FOREIGN KEY REFERENCES LeaveRequests(ID),
	[Status] INT NOT NULL,
	Comment VARCHAR(MAX) NULL
);
GO

CREATE TABLE Projects(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ProjectType INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	ProjectManagerId INT NOT NULL FOREIGN KEY REFERENCES Employees(ID),
	Comment VARCHAR(MAX) NULL,
	IsActive BIT NOT NULL
);
GO

CREATE TABLE EmployeesProjects(
	EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(ID),
	ProjectId INT NOT NULL FOREIGN KEY REFERENCES Projects(ID),
	PRIMARY KEY (EmployeeId, ProjectId)
);
GO